apiVersion: v1
kind: Pod
metadata:
  name: www
spec:
  hostNetwork: true
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    volumeMounts:
    - mountPath: /tmp/elasticsearch/data
      name: elasticsearch-vol
  - name: postgres
    image: postgres
    volumeMounts:
    - mountPath: /tmp/postgresql/data
      name: postgres-vol
  volumes:
  - name: postgres-vol
    emptyDir: {}
  - name: elasticsearch-vol
    emptyDir: {}
