apiVersion: v1
kind: Pod
metadata:
  name: www
spec:
  containers:
  - name: postgres
    image: postgres
    volumeMounts:
    - mountPath: /tmp/postgresql/data
      name: postgres-vol
  volumes:
  - name: postgres-vol
    emptyDir: {}
  - name: elasticsearch-vol
    emptyDir: {}


